### ISSUE TITLE
Converting existing react+redux+react-router App to server side render

### ISSUE THREAD

**Issue by jasan-s** [svnm/react-router-redux-example#14]
I currently have a an SPA that uses React+Redux+react-router deployed using firebase hosting. However I wanted utilize server side rendering. I am looking at this project but still unclear about how to achieve it. Can you recommend a post /article as to how to add such functionality.   Would i use something like heroku to run the server in addition to firebase hosting or would i just use heroku and not firebase hosting.

**Comment by svnm** [comment]
You would host the node/express server on something like Heroku yes that is correct. As for the front end, it could be static like on S3 or Firebase, as long as it has access to the express server. This [post](http://stackoverflow.com/questions/11181546/how-to-enable-cross-origin-resource-sharing-cors-in-the-express-js-framework-o) has some info on that.
